sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
# before_install:
#   - DOCKER_BUILDKIT=1 docker build --target=dev -t admin-docker -f Dockerfile.dev .

# script:
#   - docker run --rm --name admin -e CI=true -d -p 3000:3000 admin-docker

# after_success:
#   - docker build -t  admin-docker .
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker push  admin-docker
