language: node_js
sudo: required
node_js:
  - '9'
services:
  - docker
before_install:
  - docker build --target=dev -t admin-docker -f Dockerfile .

script:
  - docker run --rm --name admin -e CI=true -d -p 3000:3000 admin-docker

after_success:
  - docker build -t admin-docker .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  admin-docker
